language: python
python:
  - '2.7'
# command to install dependencies
install: 
  - 'easy_install -U setuptools'
  - 'pip install -U pip'
  - 'pip install -e .[tests]'
# command to run tests
script: 
  - 'nosetests -sv --with-coverage'
  - 'pip install flake8 --use-mirrors'
  - 'flake8 httpproxy --ignore=E501,W293'
