language: python
python:
- '2.7'
install:
- easy_install -U setuptools
- pip install -U pip
- pip install -e .[tests]
script:
- nosetests -sv --with-coverage
- pip install flake8 --use-mirrors
- flake8 httpproxy --ignore=E501,W293
deploy:
  provider: pypi
  server: https://pypi.vandelay.io/balanced/prod/
  user: omnibus
  password:
    secure: yji7ZyMQ7v+BSEZ1gytHW/zFYnX2TnUSlfrduoayvAIsesh2AD2tZcD0TrMuPKJyMleriLIYvM9bCC1RcdpB8LGvO/YqLXVJqIf+zH9mN+n8LAEdlHLR6ldOlPL7D3p44s9Ekz9Kg1OntoWuQ2KSpreTlthUlxvkrdDy+UfFgXI=
  on:
    all_branches: true
    tags: true
